name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i --omit=dev
      - run: npm run build --if-present

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Generate deployment package
        run: zip deploy.zip -r src dist package.json package-lock.json docker-compose.yml Dockerfile-Local tsconfig.json tsconfig.build api-gateway

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::837158764358:role/Github_actions_role
          aws-region: us-east-1
      - run: eb deploy --staged

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
      #     application_name: nest-microservices
      #     environment_name: Nestmicroservices-env
      #     version_label: ${{ github.head_ref }}.${{ github.sha }}
      #     region: us-east-1
      #     deployment_package: deploy.zip

